version: '3.7'
services:
    #React Service
    frontend:
        build:
            context: ./frontend
            dockerfile: /home/p2065/laravelprojeler/laravel9-login-api-example/frontend/docker/Dockerfile
            args:
                - NODE_ENV=development
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/usr/src/app
            - ./frontend/package.json:/usr/src/package.json
        environment:
            - NODE_ENV=development
    #PHP Service
    app:
        build:
            context: ./backend
            dockerfile: /home/p2065/laravelprojeler/laravel9-login-api-example/backend/docker/php/Dockerfile
        image: php:8.1.3-fpm
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./backend:/var/www
            - ./backend/docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./backend:/var/www
            - ./backend/docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    #MySQL Service
    db:
        image: mysql:5.7.22
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: MyselfDB
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_USER: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/
            - ./backend/docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge

#Volumes
volumes:
    dbdata:
        driver: local
